/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const currentLanguage: typeof import('./dictionary/dictionary').currentLanguage
  const dictionary: typeof import('./dictionary/dictionary').dictionary
  const dictionaryEnglish: typeof import('./dictionary/dictionary_english').dictionaryEnglish
  const dictionaryFrench: typeof import('./dictionary/dictionary_french').dictionaryFrench
  const dictionaryGerman: typeof import('./dictionary/dictionary_german').dictionaryGerman
  const dictionaryPortuguese: typeof import('./dictionary/dictionary_portuguese').dictionaryPortuguese
  const dictionarySpanish: typeof import('./dictionary/dictionary_spanish').dictionarySpanish
  const installDictionary: typeof import('./dictionary/dictionary').installDictionary
  const setLanguage: typeof import('./dictionary/dictionary').setLanguage
}
// for type re-export
declare global {
  // @ts-ignore
  export type { LanguageCode } from './dictionary/dictionary'
  import('./dictionary/dictionary')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly currentLanguage: UnwrapRef<typeof import('./dictionary/dictionary')['currentLanguage']>
    readonly dictionary: UnwrapRef<typeof import('./dictionary/dictionary')['dictionary']>
    readonly dictionaryEnglish: UnwrapRef<typeof import('./dictionary/dictionary_english')['dictionaryEnglish']>
    readonly dictionaryFrench: UnwrapRef<typeof import('./dictionary/dictionary_french')['dictionaryFrench']>
    readonly dictionaryGerman: UnwrapRef<typeof import('./dictionary/dictionary_german')['dictionaryGerman']>
    readonly dictionaryPortuguese: UnwrapRef<typeof import('./dictionary/dictionary_portuguese')['dictionaryPortuguese']>
    readonly dictionarySpanish: UnwrapRef<typeof import('./dictionary/dictionary_spanish')['dictionarySpanish']>
    readonly setLanguage: UnwrapRef<typeof import('./dictionary/dictionary')['setLanguage']>
  }
}